export const GET_PROVIDERS_BEGIN = "GET_PROVIDERS_BEGIN";

export const GET_PROVIDERS_SUCCESS = "GET_PROVIDERS_SUCCESS";

export const GET_PROVIDERS_ERROR = "GET_PROVIDERS_ERROR";

export const LOAD_MATERIAL_PROVIDERS = "LOAD_MATERIAL_PROVIDERS";
export const SET_MATERIAL_GRIDVIEW = "SET_MATERIAL_GRIDVIEW";
export const SET_MATERIAL_LISTVIEW = "SET_MATERIAL_LISTVIEW";
export const UPDATE_MATERIAL_SORT = "UPDATE_MATERIAL_SORT";
export const SORT_MATERIAL_PROVIDERS = "SORT_MATERIAL_PROVIDERS";
export const UPDATE_MATERIAL_FILTERS = "UPDATE_MATERIAL_FILTERS";
export const FILTER_MATERIAL_PROVIDERS = "FILTER_MATERIAL_PROVIDERS";
export const CLEAR_MATERIAL_FILTERS = "CLEAR_MATERIAL_FILTERS";

export const LOAD_PART_PROVIDERS = "LOAD_PART_PROVIDERS";
export const SET_PART_GRIDVIEW = "SET_PART_GRIDVIEW";
export const SET_PART_LISTVIEW = "SET_PART_LISTVIEW";
export const UPDATE_PART_SORT = "UPDATE_PART_SORT";
export const SORT_PART_PROVIDERS = "SORT_PART_PROVIDERS";
export const UPDATE_PART_FILTERS = "UPDATE_PART_FILTERS";
export const FILTER_PART_PROVIDERS = "FILTER_PART_PROVIDERS";
export const CLEAR_PART_FILTERS = "CLEAR_PART_FILTERS";
