# File: .github/workflows/deploy-dev.yml
name: Deploy to Dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t kasramahsouli/hamidi-client:${{ github.sha }} .

             # After the Docker build, list the contents of the dist folder
          docker run --rm kasramahsouli/hamidi-client:${{ github.sha }} ls -la /usr/share/nginx/html

          docker tag kasramahsouli/hamidi-client:${{ github.sha }} kasramahsouli/hamidi-client:dev
          docker push kasramahsouli/hamidi-client:dev

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install sshpass to use password-based SSH authentication
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # Use sshpass to SSH into the VPS using password authentication
      - name: SSH to VPS and Deploy using password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} << EOF
          docker pull kasramahsouli/hamidi-client:dev
          docker stop hamidi-client || true
          docker rm hamidi-client || true
          docker run -d -p 8080:80 --name hamidi-client kasramahsouli/hamidi-client:dev
          # Check the files inside the container
            docker exec hamidi-client ls -la /usr/share/nginx/html
          EOF
