# File: .github/workflows/deploy-dev.yml
name: Deploy to Dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app:${{ github.sha }} .
          docker tag my-app:${{ github.sha }} kasramahsouli/hamidi-client:dev
          docker push kasramahsouli/hamidi-client:dev

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH Connection
        run: |
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} 'echo "SSH connection successful"'

      - name: Add SSH Key
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -  # Add private key from GitHub Secrets

      # Step 2: Add VPS to known_hosts
      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEV_HOST }} >> ~/.ssh/known_hosts  # Avoids manual prompt for known hosts

      # Step 3: SSH to VPS and Deploy
      - name: SSH to VPS and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull kasramahsouli/hamidi-client:dev
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 8080:5173 --name my-app kasramahsouli/hamidi-client:dev
