# File: .github/workflows/deploy-dev.yml
name: Deploy to Dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app:${{ github.sha }} .
          docker tag my-app:${{ github.sha }} kasramahsouli/hamidi-client:dev
          docker push kasramahsouli/hamidi-client:dev

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the project (optional step if you have a build process)
      - name: Build Project
        run: |
          npm install  # Install dependencies
          npm run build  # Build the project (modify this if needed)

      # Deploy using SFTP
      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.SFTP_SERVER }} # SFTP server (e.g., your_vps_ip or sftp://your_vps_ip)
          username: ${{ secrets.SFTP_USERNAME }} # SFTP username
          password: ${{ secrets.SFTP_PASSWORD }} # SFTP password
          local-dir: ./dist # Vite's default build output directory
          server-dir: /var/wwww/ # Directory on your VPS to upload the files
          protocol: sftp # Use the SFTP protocol
