# File: .github/workflows/deploy-dev.yml
name: Deploy to Dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app:${{ github.sha }} .
          docker tag my-app:${{ github.sha }} kasramahsouli/hamidi-client:dev
          docker push kasramahsouli/hamidi-client:dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Dev Server via SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull my-docker-repo/my-app:dev
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 8080:8080 --name my-app my-docker-repo/my-app:dev
