# File: .github/workflows/deploy-prod.yml
name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version for production"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app:${{ github.sha }} .
          docker tag my-app:${{ github.sha }} my-docker-repo/my-app:prod-${{ github.event.inputs.version }}
          docker push my-docker-repo/my-app:prod-${{ github.event.inputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull my-docker-repo/my-app:prod-${{ github.event.inputs.version }}
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 80:80 --name my-app my-docker-repo/my-app:prod-${{ github.event.inputs.version }}
